# Generated by Django 5.1.6 on 2025-03-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_category_options_alter_inventoryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='artist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='dimension',
            field=models.TextField(blank=True, null=True),
        ),
    ]
