# Generated by Django 5.1.6 on 2025-03-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_inventoryitem_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='dimension',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
